language: node_js
node_js:
  - "iojs"
install:
  # aws-cloudfront-invalidate is required for invalidation of CloudFront distributions
  # aws-cloudfront-invalidate requires the use of aws-sdk
  - npm install aws-sdk aws-cloudfront-invalidate
script: echo \"No Test Needed\"
deploy:
  # deploy only on branch master
  on:
    branch: master
  provider: s3
  # AWS IAM Keys
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 bucket
  bucket: "jwaynedavidson.com"
  # Path to a directory containing built site
  # local_dir: dist
  # Set the Access Control List Permissions to Public read only
  acl: public_read
after_deploy:
  # Invalidate every object in the targeted distribution using aws-cloudfront-invalidate
  - aws-cloudfront-invalidate $CLOUD_FRONT_ID
